version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  java_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_java_app_container
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo-data: